{% set name = "dask-databricks" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_databricks-{{ version }}.tar.gz
  sha256: b8e668091ef432b21538cdb1e26abac795e25b8413db1199e1f290b6a344b4d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - click >=8.1
    - dask-core
    - rich
    - distributed

test:
  imports:
    - dask_databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jacobtomlinson/dask-databricks
  summary: Cluster tools for running Dask on Databricks
  dev_url: https://github.com/dask-contrib/dask-databricks
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobtomlinson
    - skirui-source
